version: '3'

services: 
  sonarqube:
    image: sonarqube:8.6.0-community
    ports: 
      - "9000:9000"
    networks: 
      - sonarnet
    environment:
      - SONAR_JDBC_USERNAME=sonar 
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_JDBC_URL=jdbc:postgresql://db_sonar:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_temp:/opt/sonarqube/temo
    depends_on: 
      - db_sonar

  db_sonar:
    image: postgres:9.6
    networks:
      - sonarnet
    environment: 
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_temp:
  postgresql:
  postgresql_data: