version: "3"

services:
  jenkins:
    user: root
    image: jenkinsci/blueocean:1.24.8
    container_name: jenkins
    ports:
      - "8081:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge