version: '3'

services: 
  sonarqube:
    image: sonarqube
    container_name: ci_cd_sonarqube
    ports: 
      - "9000:9000"
    networks: 
      - cicd
    environment:
      - SONAR_JDBC_USERNAME=sonar 
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_JDBC_URL=jdbc:postgresql://db_sonar:5432/sonar
    volumes:
      - ci_cd_sonarqube_conf:/opt/sonarqube/conf
      - ci_cd_sonarqube_data:/opt/sonarqube/data
      - ci_cd_sonarqube_extensions:/opt/sonarqube/extensions
      - ci_cd_sonarqube_temp:/opt/sonarqube/temo
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on: 
      - db_sonar

  db_sonar:
    image: postgres
    container_name: ci_cd_postgres
    networks:
      - cicd
    environment: 
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ci_cd_postgresql:/var/lib/postgresql
      - ci_cd_postgresql_data:/var/lib/postgresql/data

  jenkins:
    user: root
    image: jenkinsci/blueocean:1.24.8
    container_name: ci_cd_jenkins
    ports:
      - "8080:8080"
    volumes:
      - ci_cd_jenkins_home:/var/jenkins_home
      # - /usr/local/bin/docker:/usr/local/bin/docker
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/xavi/ecm_workspace/ecm_domain:/var/jenkins_home/workspace/test
    networks:
      - cicd
    depends_on:
      - sonarqube

networks:
  cicd:
    driver: bridge

volumes:
  ci_cd_sonarqube_conf:
  ci_cd_sonarqube_data:
  ci_cd_sonarqube_extensions:
  ci_cd_sonarqube_temp:
  ci_cd_postgresql:
  ci_cd_postgresql_data:
  ci_cd_jenkins_home:
